# Generated by Django 6.0 on 2026-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honermandan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honermendan',
            name='audio',
            field=models.FileField(blank=True, help_text='فایل mp3 آهنگ رو اینجا آپلود کن', null=True, upload_to='tracks/', verbose_name='فایل آهنگ'),
        ),
    ]
