# Generated by Django 6.0 on 2026-08-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honermandan_app', '0006_alter_honermendan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honermendan',
            name='genre_choice',
        ),
        migrations.RemoveField(
            model_name='honermendan',
            name='like_count',
        ),
    ]
