# Generated by Django 6.0 on 2026-09-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honermandan_app', '0007_remove_honermendan_genre_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honermendan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
