# Generated by Django 6.0 on 2026-09-12 20:09

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honermandan_app', '0008_alter_honermendan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honermendan',
            name='audio',
            field=models.FileField(blank=True, help_text='حتماً فایل mp3 را اینجا آپلود کن. فقط اسم و عکس برای پخش کافی نیست.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='tracks/', verbose_name='فایل آهنگ'),
        ),
    ]
