# Generated by Django 6.1 on 2026-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsogin_app', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
