# Generated by Django 6.0 on 2026-08-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'ژانر', 'verbose_name_plural': 'ژانرها'},
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
