# Generated by Django 6.0 on 2026-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honermandan_app', '0002_honermendan_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honermendan',
            name='audio',
            field=models.FileField(blank=True, help_text='حتماً فایل mp3 را اینجا آپلود کن. فقط اسم و عکس برای پخش کافی نیست.', null=True, upload_to='tracks/', verbose_name='فایل آهنگ'),
        ),
    ]
