# Generated by Django 6.0 on 2026-08-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres_app', '0002_alter_genre_options_delete_track'),
        ('honermandan_app', '0003_alter_honermendan_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honermendan',
            options={'verbose_name': 'هنرمند', 'verbose_name_plural': 'هنرمندان'},
        ),
        migrations.AddField(
            model_name='honermendan',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='سبک آهنگ را انتخاب کنید (مثلاً ترپ، پاپ، اولد و...)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genres_app.genre', verbose_name='ژانر / سبک'),
        ),
        migrations.AddField(
            model_name='honermendan',
            name='genre_choice',
            field=models.CharField(blank=True, choices=[('pop', 'پاپ'), ('rap', 'رپ'), ('rock', 'راک'), ('trap', 'ترپ'), ('old', 'اولد'), ('electronic', 'الکترونیک'), ('jazz', 'جاز'), ('rnb', 'آر اند بی'), ('hiphop', 'هیپ هاپ'), ('latin', 'لاتین'), ('indie', 'ایندی'), ('other', 'دیگر')], help_text='سبک آهنگ را از لیست انتخاب کنید', max_length=20, null=True, verbose_name='سبک (چند حرفه\u200cای)'),
        ),
        migrations.AddField(
            model_name='honermendan',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
    ]
