# Generated by Django 6.0 on 2026-08-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honermandan_app', '0004_alter_honermendan_options_honermendan_genre_and_more'),
        ('honermandan_app', '0004_honermendan_genre_artistlike'),
    ]

    operations = [
    ]
