# Generated by Django 6.0 on 2026-08-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres_app', '0003_seed_genres'),
        ('honermandan_app', '0005_merge_20260826_0713'),
        ('loginsogin_app', '0004_alter_customuser_options_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honermendan',
            options={},
        ),
        migrations.AlterField(
            model_name='honermendan',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='سبک این آهنگ را انتخاب کن (مثلاً ترپ، پاپ، قدیمی...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='genres_app.genre', verbose_name='سبک موسیقی'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='honermandan_app.comment', verbose_name='کامنت والد')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='honermandan_app.honermendan', verbose_name='آهنگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loginsogin_app.customuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_suggestions', to='honermandan_app.honermendan', verbose_name='آهنگ')),
            ],
            options={
                'verbose_name': 'پیشنهاد داغ',
                'verbose_name_plural': 'پیشنهادات داغ',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
