# Generated by Django 6.0 on 2026-08-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
        ('honermandan_app', '0007_remove_honermendan_genre_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured/', verbose_name='تصویر')),
                ('link_url', models.URLField(blank=True, verbose_name='لینک خارجی')),
                ('link_text', models.CharField(blank=True, max_length=200, verbose_name='متن لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محتوای ویژه',
                'verbose_name_plural': 'محتواهای ویژه',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_tracks', to='honermandan_app.honermendan', verbose_name='آهنگ')),
            ],
            options={
                'verbose_name': 'آهنگ برتر وبلاگ',
                'verbose_name_plural': 'آهنگ\u200cهای برتر وبلاگ',
                'ordering': ['order'],
            },
        ),
    ]
