# Generated by Django 6.0 on 2026-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsogin_app', '0003_customuser_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین اصلی'),
        ),
    ]
